// Seed data for the local (offline) mode of the Android app.
// IMPORTANT: The app starts EMPTY — no sample data is pre-populated.
// All collections are empty arrays. The user adds their own data.

export const SEED_DATA = {
  contacts: [],
  callLogs: [],
  events: [],
  tasks: [],
  notes: [],
  expenses: [],
  budgets: [],
  assets: [],
  accounts: [],
  debts: [],
  projects: [],
  meetings: [],
  occasions: [],
  diaryEntries: [],
  habits: [],
  medications: [],
  sleepLogs: [],
  pantryItems: [],
  waitingItems: [],
  savedLocations: [],
  contactReminders: [],
  happinessLogs: [],
  quranLogs: [],
  integrations: [
    { id: "i1", service: "google_calendar", name: "تقويم Google", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: "i2", service: "google_drive", name: "Google Drive", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: "i3", service: "telegram", name: "تيليغرام", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: "i4", service: "email", name: "البريد الإلكتروني", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: "i5", service: "github", name: "GitHub", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: "i6", service: "google_contacts", name: "جهات اتصال Google", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
    { id: "i7", service: "cloud_sync", name: "مزامنة سحابية", connected: false, config: null, lastSync: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  ],
  scheduledMessages: [],
  automationRules: [],
  suggestions: [],
  activityLogs: [],
  appSettings: [
    { id: "as1", key: "username", value: "المستخدم" },
    { id: "as2", key: "theme", value: "dark" },
    { id: "as3", key: "city", value: "حلب" },
    { id: "as4", key: "lat", value: "36.2021" },
    { id: "as5", key: "lng", value: "37.1343" },
    { id: "as6", key: "timezone", value: "Asia/Damascus" },
    { id: "as7", key: "exchangeRate", value: "12500" },
    { id: "as8", key: "aiApiKey", value: "2c7a65f8bee345fb80eee4575deb5bbf.3WE0RlXGJ2CZicJT" },
    { id: "as9", key: "aiModel", value: "glm-4.5-flash" },
    { id: "as10", key: "aiBaseUrl", value: "https://api.z.ai/api/paas/v4" },
  ],
};
